#!/usr/bin/python           

# This is server.py file

import socket               # Import socket module

s = socket.socket()         # Create a socket object
host = socket.gethostname() # Get local machine name
port = 9999                # Reserve a port for your service.
s.bind((host, port))        # Bind to the port

s.listen(5)                 # Now wait for client connection.

reqnum = 1

print 'Server started.'

while True:
   c, addr = s.accept()     # Establish connection with client.
   msg = c.recv(1024)
   print 'Got message (' + str(reqnum) + ') [' + msg + '] from', addr
   c.send('Request ' + str(reqnum) + ' received.')
   c.close()                # Close the connection
   
   # spawn a thread to process the request
   print 'Can the failure be handled? If so, take appropriate action by automatic scripts or administrators.'   
   print 'Check if the failure is in the fault-event-action table. If not, call administrators.'
   if '111' in msg:
	print 'stop-firewall'
#	stop-firewall

   reqnum += 1
